name: 10 Build

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:

    name: Build Java
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # compile
      - name: Build with Maven
        run: mvn clean package -B -Dmaven.test.skip
      - run: mkdir staging && cp target/*.jar staging
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-target
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.m2/**/*.jar
          key: ${{ runner.os }}-m2
      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: ${{ github.workspace }}/target
          retention-days: 5

      # test
      - name: Test with Maven
        run: mvn test
      - run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: always()
        with:
          junit_files: "test-results/**/*.xml"
               