# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 10 Build

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    name: Build Java
    #runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # compile
      - name: Build with Maven
        run: mvn clean package -B -Dmaven.test.skip
      - run: mkdir staging && cp target/*.jar staging
      # test
      - name: Test with Maven
        run: mvn test
      - run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results
      # upload
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: always()
        with:
          junit_files: "test-results/**/*.xml"
               