name: 00 CI Deploy Azure

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  deploy-to-azure:
    name: Deploy to Azure
    permissions:
      packages: read
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spring-petclinic-rest-public'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ needs.docker.outputs.image-name-with-tag }}
