name: 00 CI Development

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
    paths-ignore:
      - '**/".md'
      - '**/".txt'

jobs:
  build:
   name: Build
   permissions:
     contents: read
     issues: read
     checks: write
     pull-requests: write
     packages: write
   uses: ./.github/workflows/build.yml
   secrets: inherit
   if: ${{ github.event_name != 'pull_request' }}

  # deploy docker image to azure