name: 00 CI Deploy Azure

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    name: Build Maven
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn package --batch-mode

      - name: Save compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: target/*.jar
          retention-days: 1

  docker:
    name: Build Docker Image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image-name-with-tag: ${{ steps.meta.outputs.tags }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download application binary
      uses: actions/download-artifact@v3.0.0
      with:
        name: app
        path: target

    - name: Log in to the Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.1.0
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy-to-azure:
    name: Deploy to Azure
    permissions:
      packages: read
    runs-on: ubuntu-latest
    needs: docker
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spring-petclinic-rest-public'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ needs.docker.outputs.image-name-with-tag }}
