name: 00 Continuous Integration

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'feature/**'
#      - 'hotfix/**'
#    paths-ignore:
#      - '**/".md'
#      - '**/".txt'

jobs:
  build:
    # why we need to add permissions here???
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
