name: 12 Scan Image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "The name of the docker image to scan"
        required: true
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: "The name of the docker image to scan"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.image-tag || github.event.inputs.image-tag }}

jobs:

  container-image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3