name: 12 Scan Image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "The name of the docker image to scan"
        required: true
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: "The name of the docker image to scan"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.image-tag || github.event.inputs.image-tag }}

jobs:

  container-image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Image
      run: docker pull ${{ env.IMAGE_NAME }}

    # https://github.com/aquasecurity/trivy-action
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.7.1
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        hide-progress: false
        timeout: 10m

    - name: Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'