name: 20 Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:

    name: Deploy Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Publish to GitHub Packages
        run: mvn deploy --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               
      # not needed if available in GitHub Packages..
      - name: Copy artifacts to staging directory
        run: mkdir staging && cp target/*.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ github.workspace }}/staging
          retention-days: 5