name: 30 License

on:
  workflow_dispatch:
  workflow_call:

jobs:

  license-finder:

    name: License Finder
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: License Finder fix
        run: rm mvnw

      - name: License Finder
        uses: jmservera/license-finder-action@v0.1.4-alpha
        with:
          permitted-licenses: MIT,Apache-2.0
          approved-dependencies: jquery,bootstrap

      - name: Publish license results
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: always()
        with:
          junit_files: "license_finder_report.xml"
          check_name: "License Finder Results"
          comment_title: "License Finder Results"

      - name: Upload Dependency Review Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: license-finder-report
          path: license_finder_report.xml
