name: 00 Build Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/".md'
      - '**/".txt'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      checks: write
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  sca:
    permissions:
      checks: write
      security-events: write
      actions: read
      contents: read
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit